name: 'pitfall_a2c_simple'
seed: 2019

env:
  name: waterboy.rl.env.atari.classic_atari
  game: 'PitfallNoFrameskip-v0'

vec_env:
  name: waterboy.rl.vecenv.subproc
  frame_history: 4  # How many stacked frames go into a single observation


model:
  name: waterboy.models.rl.nature_cnn
  input_width: 84
  input_height: 84
  input_channels: 4  # The same as frame_history


reinforcer:
  name: waterboy.rl.reinforcers.policy_gradient

  policy_gradient:
    name: waterboy.rl.reinforcers.policy_gradient.a2c
    entropy_coefficient: 0.01
    value_coefficient: 0.5

  number_of_steps: 5 # How many environment steps go into a single batch
  parallel_envs: 16 # How many environments to run in parallel
  discount_factor: 0.99

  max_grad_norm: 0.5


optimizer:
  name: waterboy.optimizers.rmsprop
  lr: 7.0e-4
  alpha: 0.99


commands:
  train:
    name: waterboy.rl.commands.rl_train
    total_frames: 1.1e7
    batches_per_epoch: 100
  play:
    name: waterboy.commands.rl.ai_play
