language: "python"
dist: xenial
sudo: true
python:
  - "3.6"
# Command to install dependencies
install:
  - sudo apt install -q libopenmpi-dev swig
  - pip install --quiet -r travis-requirements.txt
# Command to run tests
script:
  - nosetests