storage:
  name: waterboy.storage.classic

  backend:
    name: waterboy.storage.backend.mongodb
    uri: 'mongodb://localhost:27017/'
    database: deep_learning

  streaming:
    - name: waterboy.storage.streaming.visdom
    - name: waterboy.storage.streaming.stdout


checkpoint_strategy:
  name: waterboy.storage.strategy.classic_checkpoint_strategy


visdom_settings:
  stream_lr: false

