name: 'mnist_cnn_01'


model:
  name: waterboy.models.classification.mnist_cnn_01
  img_rows: 28
  img_cols: 28
  img_channels: 1
  num_classes: 10


source:
  name: waterboy.sources.classic.mnist
  batch_size: 128
  normalize: False
  num_workers: 4


commands:
  train:
    name: waterboy.commands.train
    epochs: 12
    log_frequency: 100

    optimizer:
      name: waterboy.optimizers.adadelta

    checkpoint:
      metric: 'val:loss'

  visdom:
    name: waterboy.commands.vis_store
