name: 'mnist_fc_vae'


model:
  name: vel.model.autoencoder.fc_vae
  img_rows: 28
  img_cols: 28
  img_channels: 1
  layers: [200, 200]
  representation_length: 50
  max_grad_norm: 1.0
  analytical_kl_div: true


source:
  name: vel.data.source.vision.mnist

loader:
  name: vel.data.dataset_loader
  batch_size: 128
  num_workers: 4
  pin_memory: true

  transformations:
    - name: vel.data.transformation.to_array
    - name: vel.data.transformation.binarize_image
    - name: vel.data.transformation.image_to_tensor
    - name: vel.data.transformation.unsupervised


optimizer:
  name: vel.optimizer.radam
  lr: 1.0e-3
  eps: 1.0e-4


scheduler:
  name: vel.scheduler.multi_step
  gamma: 0.71968  # 10 * (-1/7)
  milestones: [   1,    4,   13,   40,  121,  364, 1093, 3280]


commands:
  train:
    name: vel.command.train_command
    epochs: 3280

#  train:
#    name: vel.command.phase_train_command
#    phases:
#      - name: vel.train.phase.cycle
#        max_lr: 0.001
#        min_lr: 0.000
#        interpolate: 'cosine'
#        cycles: 20
#        cycle_len: 1
#      - name: vel.train.phase.cycle
#        max_lr: 0.001
#        min_lr: 0.0000
#        interpolate: 'cosine'
#        cycles: 7
#        cycle_len: 1
#        cycle_mult: 2
#      - name: vel.train.phase.cycle
#        max_lr: 0.0001
#        min_lr: 0.0000
#        interpolate: 'cosine'
#        cycles: 8
#        cycle_len: 1
#        cycle_mult: 2
#      - name: vel.train.phase.cycle
#        max_lr: 0.00003
#        min_lr: 0.0000
#        interpolate: 'cosine'
#        cycles: 9
#        cycle_len: 1
#        cycle_mult: 2
#      - name: vel.train.phase.cycle
#        max_lr: 0.00001
#        min_lr: 0.0000
#        interpolate: 'cosine'
#        cycles: 10
#        cycle_len: 1
#        cycle_mult: 2
