name: 'mnist_fc_vae'


model:
  name: vel.model.autoencoder.mnist_fc_vae
  img_rows: 28
  img_cols: 28
  img_channels: 1
  layers: [512, 256]
  representation_length: 16


source:
  name: vel.data.source.vision.mnist

loader:
  name: vel.data.dataset_loader
  batch_size: 256
  num_workers: 4

  transformations:
    - name: vel.data.transformation.image_to_tensor
    - name: vel.data.transformation.unsupervised


optimizer:
  name: vel.optimizer.radam
  lr: 1.0e-3


commands:
  train:
    name: vel.command.train_command
    epochs: 100

