name: 'breakout_ppo_simple'
seed: 2019

env:
  name: waterboy.rl.env.atari.classic_atari
  game: 'BreakoutNoFrameskip-v4'


vec_env:
  name: waterboy.rl.vecenv.subproc
  frame_history: 4  # How many stacked frames go into a single observation


model:
  name: waterboy.rl.reinforcers.policy_gradient.policy_gradient_model
  backbone:
    name: waterboy.models.rl.nature_cnn
    input_width: 84
    input_height: 84
    input_channels: 4  # The same as frame_history


reinforcer:
  name: waterboy.rl.reinforcers.policy_gradient

  policy_gradient:
    name: waterboy.rl.reinforcers.policy_gradient.ppo
    entropy_coefficient: 0.01
    value_coefficient: 0.5

    cliprange: 0.1
    cliprange_scaling: 'linear'

  number_of_steps: 128 # How many environment steps go into a single batch
  parallel_envs: 8 # How many environments to run in parallel
  batch_size: 256 # How many samples can go into the model once
  experience_replay: 4 # How many times to replay the experience

  discount_factor: 0.99 # Discount factor for the rewards
  gae_lambda: 0.95 # Generalized Advantage Estimator Lambda parameter

  max_grad_norm: 0.5 # Gradient clipping parameter


optimizer:
  name: waterboy.optimizers.adam
  lr: 2.5e-4
  epsilon: 1.0e-5


scheduler:
  name: waterboy.scheduler.linear_batch_scaler


commands:
  train:
    name: waterboy.rl.commands.rl_train_command
    total_frames: 1.1e7
    batches_per_epoch: 10

  record:
    name: waterboy.rl.commands.record_movie_command
    takes: 10
    videoname: 'breakout_ppo_vid_{:04}.avi'
