name: cats_vs_dogs_resnet34


model:
  name: vel.models.imagenet.resnet34
  fc_layers: [512, 2]
  dropout: [0.25, 0.5]
  pretrained: true


source:
  name: vel.sources.img_dir_source
  # Dataset downloaded from http://files.fast.ai/data/dogscats.zip
  path: data/dogscats
  num_workers: 8
  batch_size: 64

#  tta:
#    name: vel.augmentations.tta.train_tta
#    n_augmentations: 4

  augmentations:
  - name: vel.augmentations.to_array
    mode: x
    tags: ["train", "val"]

  - name: vel.augmentations.random_scale
    mode: x
    tags: ["train"]
    size: 224
    max_zoom: 1.1
  - name: vel.augmentations.random_rotate
    mode: x
    tags: ["train"]
    deg: 10.0
  - name: vel.augmentations.random_crop
    mode: x
    tags: ["train"]
    width: 224
    height: 224
  - name: vel.augmentations.random_lighting
    mode: x
    tags: ["train"]
    b: 0.05
    c: 0.05
  - name: vel.augmentations.random_horizontal_flip
    mode: x
    tags: ["train"]

  - name: vel.augmentations.scale_min_size
    mode: x
    tags: ["val"]
    size: 224
  - name: vel.augmentations.center_crop
    mode: x
    tags: ["val"]
    size: 224

  - name: vel.augmentations.normalize
    mode: x
    tags: ["train", "val"]
    mean: [0.485, 0.456, 0.406]
    std:  [0.229, 0.224, 0.225]

  - name: vel.augmentations.to_tensor
    mode: x
    tags: ["train", "val"]


optimizer:
  name: vel.optimizers.sgd
  lr: 0.01
  weight_decay: 0.0
  momentum: 0.9


commands:
  train:
    name: vel.commands.phase_train_command
    restart: false
    phases:
    - name: vel.phase.freeze
    - name: vel.phase.cycle
      init_lr: 0.001
      init_iter: 20
      max_lr: 0.01
      min_lr: 0.00
      interpolate: 'cosine'
      cycles: 3
      cycle_len: 1
    - name: vel.phase.unfreeze
    - name: vel.phase.cycle
      init_lr: 0.001
      init_iter: 20

      max_lr: [1.0e-4, 1.0e-3, 1.0e-2]
      min_lr: [0.0, 0.0, 0.0]
      interpolate: 'cosine'
      cycles: 3
      cycle_len: 1
      cycle_mult: 2

  simple_train:
    name: vel.commands.train_command
    restart: false
    epochs: 3

  summary:
    name: vel.commands.summary_command

  lr_find:
    name: vel.commands.lr_find_command
    metric: 'loss'
    start_lr: 1.0e-5
    end_lr: 10.0
    iterations: 500
    divergence_threshold: 4.0
    freeze: true

  augvis:
    name: vel.commands.augvis_command
#    seed: 1
    cases: 3
    samples: 4
